In [2]:
import pandas as pd
import numpy as np

In [3]:
tag = ['RB','NN','TO']

In [6]:
transition_counts = {
    ('NN', 'NN'): 16241,
    ('RB', 'RB'): 2263,
    ('TO', 'TO'): 2,
    ('NN', 'TO'): 5256,
    ('RB', 'TO'): 855,
    ('TO', 'NN'): 734,
    ('NN', 'RB'): 2431,
    ('RB', 'NN'): 358,
    ('TO', 'RB'): 200
}

In [10]:
num_tag = len(tag)
trans_matrix = np.zeros((num_tag,num_tag))
trans_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
sorted_tag = sorted(tag)
sorted_tag

['NN', 'RB', 'TO']

In [16]:
for i in range(len(sorted_tag)):
    for j in range(len(sorted_tag)):
        get_tag = (sorted_tag[i],sorted_tag[j])
        trans_matrix[i, j] = transition_counts.get(get_tag)

trans_matrix

array([[1.6241e+04, 2.4310e+03, 5.2560e+03],
       [3.5800e+02, 2.2630e+03, 8.5500e+02],
       [7.3400e+02, 2.0000e+02, 2.0000e+00]])

In [58]:
trans_matrix =  pd.DataFrame(trans_matrix,index=sorted_tag, columns=sorted_tag)
trans_matrix

         NN      RB      TO
NN  16241.0  2431.0  5256.0
RB    358.0  2263.0   855.0
TO    734.0   200.0     2.0

In [60]:
np.sum([i for i in trans_matrix.loc['RB']])

3476.0

In [ ]:
sum_of_row = [sum for i in range(len(trans_matrix)) for]

In [50]:
for i in sorted_tag:
    trans_matrix['SUM'] = np.sum([j for j in trans_matrix.loc[i]])

In [56]:
trans_matrix

         NN      RB      TO      SUM
NN  16241.0  2431.0  5256.0  28340.0
RB    358.0  2263.0   855.0  28340.0
TO    734.0   200.0     2.0  28340.0

In [ ]:
for i in range(len(trans_matrix)):